version: '3'

services:
  web:
    build: .
    command: >
      bash -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - secrets.env
    environment:
      - "DJANGO_SECRET_KEY"
      - "DATABASE_ENGINE=django.db.backends.postgresql"
      - "DATABASE_DB=django_db"
      - "DATABASE_HOST=vt_postgres"
      - "DJANGO_DEBUG=True"
    labels:
      - traefik.enable=true
      - traefik.http.routers.youtube.rule=Host(`youtube.dplab.biz`)
      - traefik.http.routers.youtube.entrypoints=https
      - traefik.http.routers.youtube.tls=true
      - traefik.http.routers.youtube.tls.certresolver=letsencrypt
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - vt_postgres

  huey:
    build: .
    command: >
      bash -c "python3 manage.py run_huey --logfile huey.log"
    env_file:
      - secrets.env
    environment:
      - "DJANGO_SECRET_KEY"
      - "DATABASE_ENGINE=django.db.backends.postgresql"
      - "DATABASE_DB=django_db"
      - "DATABASE_HOST=vt_postgres"
      - "DATABASE_PORT=5432"
      - "DJANGO_DEBUG=True"

    volumes:
      - .:/code
    depends_on:
      - vt_postgres

  vt_postgres:
    image: library/postgres:latest

    volumes:
      - ./postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    env_file:
      - secrets.env
    environment:
      - "POSTGRES_DB=django_db"



networks:
  default:
    external:
      name: projects_traefik
